[project]
name = "baseline"
version = "0.1.0"
description = "A simple GPT baseline"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gnureadline>=8.2.13",
    "ipdb>=0.13.13",
    "numpy>=2.3.4",
    "torch>=2.9.0",
]
